"use client";
import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import dynamic from 'next/dynamic';
import { Bone, Brain, Heart, Layers3, Activity, MoveUpRight, MousePointer2, RotateCcw, ZoomIn, ZoomOut, Maximize, Scan, Eye, EyeOff, Search, ChevronRight, BookOpen, Check, Info, X, ArrowRight, GraduationCap, Lightbulb, StickyNote, CheckCheck, CircleHelp, LoaderCircle, ListFilter } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Progress } from '@/components/ui/progress';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sidebar, SidebarProvider, SidebarContent } from '@/components/ui/sidebar';
import { SYSTEMS, QUESTIONS, getSystem, describe, type Structure, type SystemId } from '@/lib/anatomy/content';
import type { ViewerHandle } from '@/components/anatomy/Viewer';
const Viewer=dynamic(()=>import('@/components/anatomy/Viewer'),{ssr:false,loading:()=> <div className="model-status"><LoaderCircle className="spin"/>Preparing your 3D view…</div>});
const icons={skeletal:Bone,muscular:Activity,nervous:Brain,organs:Heart,ligaments:Layers3};
const defaults:Record<SystemId,RegExp>={skeletal:/^Right femur$/i,muscular:/^Right (?:acromial part of )?deltoid(?: muscle)?$/i,nervous:/^Right precentral gyrus$/i,organs:/^Heart$/i,ligaments:/^Right long plantar ligament$/i};
const STORAGE='anatomy-atlas-study-v1';
type Study={studied:string[];notes:Record<string,string>;scores:Partial<Record<SystemId,number>>};
const emptyStudy:Study={studied:[],notes:{},scores:{}};
export default function Home(){
 const [structures,setStructures]=useState<Structure[]>([]),[manifestError,setManifestError]=useState(false),[reload,setReload]=useState(0);
 const [system,setSystem]=useState<SystemId>('skeletal'),[selected,setSelected]=useState<string|null>(null),[isolated,setIsolated]=useState(false),[opacity,setOpacity]=useState(100),[context,setContext]=useState(true),[labels,setLabels]=useState(true),[orientation,setOrientation]=useState('front');
 const [library,setLibrary]=useState(false),[search,setSearch]=useState(''),[studiedOnly,setStudiedOnly]=useState(false),[help,setHelp]=useState(false),[sources,setSources]=useState(false),[quiz,setQuiz]=useState(false),[questionIndex,setQuestionIndex]=useState(0),[answer,setAnswer]=useState<number|null>(null),[score,setScore]=useState(0),[complete,setComplete]=useState(false);
 const [study,setStudy]=useState<Study>(emptyStudy),[storageReady,setStorageReady]=useState(false),[storageError,setStorageError]=useState(false),[readySystem,setReadySystem]=useState<SystemId|null>(null),[detailTab,setDetailTab]=useState('overview');
 const viewer=useRef<ViewerHandle>(null);const viewport=useRef<HTMLElement>(null);
 useEffect(()=>{const abort=new AbortController();setManifestError(false);fetch('/models/manifest.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw Error();return r.json() as Promise<Structure[]>}).then((data:Structure[])=>{if(!Array.isArray(data)||!data.length)throw Error();setStructures(data);setSelected(data.find(s=>defaults.skeletal.test(s.name))?.id||data[0].id)}).catch(e=>{if(e.name!=='AbortError')setManifestError(true)});return()=>abort.abort()},[reload]);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE);if(raw){const data=JSON.parse(raw);setStudy({studied:Array.isArray(data.studied)?data.studied.filter((x:unknown)=>typeof x==='string'):[],notes:data.notes&&typeof data.notes==='object'?Object.fromEntries(Object.entries(data.notes).filter(([,v])=>typeof v==='string')) as Record<string,string>:{},scores:data.scores&&typeof data.scores==='object'?Object.fromEntries(Object.entries(data.scores).filter(([,v])=>typeof v==='number'&&v>=0&&v<=5)):{}})}}catch{setStorageError(true)}setStorageReady(true)},[]);
 useEffect(()=>{if(storageReady)try{localStorage.setItem(STORAGE,JSON.stringify(study))}catch{setStorageError(true)}},[study,storageReady]);
 const current=structures.find(s=>s.id===selected),sys=getSystem(system),Icon=icons[system],description=current?describe(current):null;
 const systemStructures=useMemo(()=>structures.filter(s=>s.system===system),[structures,system]);
 const studiedCount=systemStructures.filter(s=>study.studied.includes(s.id)).length;
 const changeSystem=useCallback((id:SystemId)=>{setSystem(id);setSelected(structures.find(s=>s.system===id&&defaults[id].test(s.name))?.id||structures.find(s=>s.system===id)?.id||null);setIsolated(false);setOpacity(100);setOrientation('front');setDetailTab('overview');setSearch('');setStudiedOnly(false);setReadySystem(null);viewer.current?.reset()},[structures]);
 const selectStructure=useCallback((id:string)=>{const s=structures.find(s=>s.id===id);if(!s)return;if(s.system!==system){setSystem(s.system);setReadySystem(null)}setSelected(id);setLibrary(false);setDetailTab('overview')},[structures,system]);
 const onReady=useCallback((id:SystemId)=>setReadySystem(id),[]);
 const toggleStudied=()=>{if(selected)setStudy(p=>({...p,studied:p.studied.includes(selected)?p.studied.filter(id=>id!==selected):[...p.studied,selected]}))};
 const reset=()=>{setIsolated(false);setOrientation('front');setOpacity(100);viewer.current?.reset()};
 const startQuiz=()=>{setQuestionIndex(0);setAnswer(null);setScore(0);setComplete(false);setQuiz(true)};
 const nextQuestion=()=>{if(questionIndex===QUESTIONS[system].length-1){setComplete(true);setStudy(p=>({...p,scores:{...p.scores,[system]:Math.max(p.scores[system]||0,score)}}))}else{setQuestionIndex(i=>i+1);setAnswer(null)}};
 useEffect(()=>{const handle=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setLibrary(v=>!v)}};document.addEventListener('keydown',handle);return()=>document.removeEventListener('keydown',handle)},[]);
 useEffect(()=>{const modelContext=(document as Document&{modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!modelContext?.registerTool)return;const controller=new AbortController();
 const tools=[{name:'list_anatomy_structures',description:'List structures in the local anatomy atlas, optionally filtered by system and name.',inputSchema:{type:'object',properties:{system:{type:'string',enum:SYSTEMS.map(s=>s.id)},query:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:{system?:SystemId;query?:string})=>{if(input.system&&!SYSTEMS.some(s=>s.id===input.system))throw Error('Unknown system');if(input.query!==undefined&&typeof input.query!=='string')throw Error('Query must be text');return structures.filter(s=>(!input.system||s.system===input.system)&&(!input.query||s.name.toLowerCase().includes(input.query.toLowerCase()))).map(({id,name,system})=>({id,name,system}))}},
 {name:'select_anatomy_structure',description:'Select an existing structure in the 3D atlas and open its learning panel.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:{id:string})=>{const s=structures.find(s=>s.id===input.id);if(!s)throw Error('Unknown structure');selectStructure(s.id);await new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve())));return{id:s.id,name:s.name,system:s.system}}}];
 for(const tool of tools)try{void Promise.resolve(modelContext.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}return()=>controller.abort();},[structures,selectStructure]);
 const filtered=structures.filter(s=>(search.trim()?s.name.toLowerCase().includes(search.toLowerCase().trim()):s.system===system)&&(!studiedOnly||study.studied.includes(s.id)));
 const question=QUESTIONS[system][questionIndex];
 return <main className="app"><header className="topbar"><a className="brand" href="/" aria-label="Anatomy Atlas home"><span className="brand-mark"><Layers3 size={22}/></span>anatomy<span className="brand-light">atlas</span></a><span className="top-divider"/><span className="top-label">Anatomy, in every dimension.</span><div className="header-actions"><span className="learning-count"><CheckCheck size={15}/>{study.studied.length} studied</span><Button variant="outline" className="practice-button" onClick={startQuiz}><GraduationCap size={17}/>Practice</Button><button className="help-button" onClick={()=>setHelp(true)} aria-label="Help and keyboard shortcuts"><CircleHelp size={19}/></button></div></header>
 <SidebarProvider className="workspace" style={{'--sidebar-width':'100%'} as React.CSSProperties}><Sidebar collapsible="none" className="systems-panel"><SidebarContent className="system-content"><div><div className="eyebrow">THE HUMAN BODY</div><h1>Explore anatomy</h1><p className="muted">A closer look at what makes us.</p></div><button className="search-launch" onClick={()=>setLibrary(true)}><Search size={16}/><span>Find a structure</span><kbd>⌘ K</kbd></button><div className="panel-title">BODY SYSTEMS <span>05</span></div><div className="system-list">{SYSTEMS.map(s=>{const I=icons[s.id];return <button key={s.id} aria-pressed={system===s.id} className={'system-card '+(system===s.id?'active':'')} onClick={()=>changeSystem(s.id)}><span className="system-symbol" style={{color:s.color}}><I size={22}/></span><span>{s.name}<small>{structures.filter(x=>x.system===s.id).length||'—'} structures</small></span><MoveUpRight size={15}/></button>})}</div><div className="layer-settings"><div className="panel-title">VIEW SETTINGS<Layers3 size={14}/></div><div className="setting-label"><label id="opacity-label">Layer opacity</label><span>{opacity}%</span></div><Slider aria-labelledby="opacity-label" value={[opacity]} onValueChange={v=>setOpacity(v[0])} min={15} max={100} step={5}/><div className="toggle-row"><label htmlFor="labels">Structure label</label><Switch id="labels" checked={labels} onCheckedChange={setLabels} size="sm"/></div><div className="toggle-row"><label htmlFor="context">Skeleton reference</label><Switch id="context" checked={context} onCheckedChange={setContext} disabled={system==='skeletal'||isolated} size="sm"/></div></div><div className="sidebar-note"><Lightbulb size={18}/><span>Follow your curiosity.<small>Select any structure to uncover the details.</small></span></div><button className="source-link" onClick={()=>setSources(true)}><Info size={13}/>About this atlas & sources</button></SidebarContent></Sidebar>
 <section className="viewer-panel" ref={viewport} aria-label="3D anatomy explorer"><div className="viewer-heading"><div className="breadcrumb">3D ATLAS <span>/</span> {isolated?'ISOLATED STRUCTURE':'FULL BODY'}</div><h2>{sys.name}{system==='organs'?'':' system'}</h2><p>Adult reference anatomy <span className="dot-separator">·</span> {orientation==='back'?'Posterior':orientation==='side'?'Lateral':'Anterior'} preset</p></div><div className="model-badge"><span className={readySystem===system?'ready-dot':'pending-dot'}/>{readySystem===system?'LIVE 3D':'LOADING'}</div>
 {structures.length>0?<Viewer ref={viewer} system={system} structures={structures} selected={selected} isolated={isolated} opacity={opacity} context={context} labels={labels} onSelect={selectStructure} onReady={onReady}/>:manifestError?<div className="model-error" role="alert"><Info/><h3>The atlas couldn’t load</h3><p>Check that the local server is running, then try again.</p><Button onClick={()=>setReload(n=>n+1)}>Try again</Button></div>:<div className="model-status"><LoaderCircle className="spin"/>Opening your anatomy atlas…</div>}
 <div className="orientation-marks" aria-hidden="true"><span>R</span><span>L</span></div><div className="viewer-tools"><button title="Zoom in (+)" aria-label="Zoom in" onClick={()=>viewer.current?.zoom(.8)}><ZoomIn size={19}/></button><button title="Zoom out (-)" aria-label="Zoom out" onClick={()=>viewer.current?.zoom(1.25)}><ZoomOut size={19}/></button><span/><button title="Focus selected structure" aria-label="Focus selected structure" onClick={()=>viewer.current?.focus()}><Scan size={19}/></button><button title="Reset full body view (0)" aria-label="Reset full body view" onClick={reset}><Maximize size={18}/></button></div>
 {isolated&&<button className="isolated-badge" onClick={()=>{setIsolated(false);viewer.current?.reset()}}><EyeOff size={13}/>Isolated view<X size={13}/></button>}
 <div className="view-presets" aria-label="Camera presets">{[{id:'front',label:'Front'},{id:'back',label:'Back'},{id:'side',label:'Side'}].map(s=><button key={s.id} aria-pressed={orientation===s.id} className={orientation===s.id?'selected':''} onClick={()=>{setOrientation(s.id);viewer.current?.orient(s.id as 'front'|'back'|'side')}}>{s.label}</button>)}</div>
 <div className="viewer-footer"><span><MousePointer2 size={14}/>Click again to select the structure underneath <span>·</span> Drag to rotate</span><Button variant="outline" onClick={reset}><RotateCcw size={14}/>Reset view</Button></div>
 </section>
 <aside className="details-panel"><div className="detail-eyebrow"><span className="eyebrow">STRUCTURE INSIGHT</span><button onClick={()=>setLibrary(true)} aria-label="Browse all structures" title="Browse structures"><ListFilter size={18}/></button></div>{current&&description?<><div className="structure-class"><Icon size={14}/>{sys.name.toUpperCase()}<span>{current.fma}</span></div><h2 className="structure-name">{current.name}</h2>{description.latin&&<p className="latin">{description.latin}</p>}<div className="structure-tags"><span>{current.name.toLowerCase().startsWith('right')?'Right side':current.name.toLowerCase().startsWith('left')?'Left side':'Human anatomy'}</span><span>3D structure</span></div><div className="structure-actions"><Button variant={isolated?'default':'outline'} onClick={()=>{if(isolated)viewer.current?.reset();setIsolated(v=>!v)}} aria-pressed={isolated}>{isolated?<Eye/>:<Scan/>}{isolated?'Show all':'Isolate'}</Button><Button variant="outline" onClick={()=>viewer.current?.focus()}><Maximize/>Focus</Button></div>
 <Tabs value={detailTab} onValueChange={setDetailTab} className="detail-tabs"><TabsList variant="line"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="notes">My notes {study.notes[current.id]?.trim()&&<span className="note-dot"/>}</TabsTrigger></TabsList><TabsContent value="overview"><p className="structure-summary">{description.summary}</p><h3 className="section-label">{description.specific?'PRIMARY FUNCTION':'SYSTEM CONTEXT'}</h3><p className="function-text">{description.function}</p><div className="remember-card"><div><Lightbulb size={16}/><span>Make the connection</span></div><p>{description.remember}</p></div><button className="browse-structures" onClick={()=>setLibrary(true)}><span><Layers3 size={16}/>Explore {systemStructures.length} structures</span><ChevronRight size={17}/></button></TabsContent><TabsContent value="notes"><label htmlFor="study-note" className="note-label">Your observations</label><Textarea id="study-note" placeholder="What did you notice? Add a memory cue, connection, or question…" className="study-note" value={study.notes[current.id]||''} maxLength={6000} onChange={e=>setStudy(p=>({...p,notes:{...p.notes,[current.id]:e.target.value}}))}/><p className="note-saved"><StickyNote size={13}/>{storageError?'Storage unavailable; notes last for this session.':'Saved automatically on this browser.'}</p></TabsContent></Tabs>
 <div className="study-progress"><div className="progress-heading"><span>Your exploration</span><span>{studiedCount} / {systemStructures.length}</span></div><Progress value={systemStructures.length?studiedCount/systemStructures.length*100:0} aria-label="Studied structures in this system"/><Button variant={study.studied.includes(current.id)?'secondary':'default'} className="studied-button" onClick={toggleStudied}><Check size={16}/>{study.studied.includes(current.id)?'Studied · click to undo':'Mark as studied'}</Button></div></>:<div className="empty-insight"><BookOpen/><p>Select a structure to start exploring.</p></div>}
 <div className="source-footer">Z-ANATOMY / BODYPARTS3D<button onClick={()=>setSources(true)}>Educational reference · View coverage<MoveUpRight size={11}/></button></div></aside></SidebarProvider>
 <Dialog open={library} onOpenChange={setLibrary}><DialogContent className="library-dialog"><DialogHeader><DialogTitle>Find your next discovery</DialogTitle><DialogDescription>Search across all five systems, or browse {sys.name.toLowerCase()} structures.</DialogDescription></DialogHeader><div className="library-search"><Search size={19}/><Input aria-label="Search anatomy structures" placeholder="Try femur, deltoid, heart…" value={search} onChange={e=>setSearch(e.target.value)} autoFocus/></div><div className="library-filter"><span>{filtered.length} structures</span><button className={studiedOnly?'active':''} aria-pressed={studiedOnly} onClick={()=>setStudiedOnly(v=>!v)}><CheckCheck size={14}/>Studied only</button></div><div className="structure-results">{filtered.length?filtered.map(s=>{const I=icons[s.system];return <button key={s.id} onClick={()=>selectStructure(s.id)}><span className="result-icon" style={{color:getSystem(s.system).color}}><I size={20}/></span><span>{s.name}<small>{getSystem(s.system).name} · {s.fma}</small></span>{study.studied.includes(s.id)?<Check size={17}/>:<ChevronRight size={17}/>}</button>}):<div className="empty-results"><Search size={26}/><h3>No structures found</h3><p>Try a broader name{studiedOnly?' or turn off the studied filter':''}.</p><Button variant="outline" onClick={()=>{setSearch('');setStudiedOnly(false)}}>Clear filters</Button></div>}</div></DialogContent></Dialog>
 <Dialog open={quiz} onOpenChange={setQuiz}><DialogContent className="quiz-dialog"><DialogHeader><span className="quiz-icon"><GraduationCap size={26}/></span><DialogTitle>{complete?'A little more knowledge.':'Put your knowledge to work.'}</DialogTitle><DialogDescription>{sys.name} practice · Five questions · No timer</DialogDescription></DialogHeader>{complete?<div className="quiz-complete"><div className="score-ring">{score}<span>/ 5</span></div><h3>{score===5?'You know your anatomy.':score>=3?'Good progress. Keep exploring.':'Every question is a chance to learn.'}</h3><p>Best score in this browser: {Math.max(study.scores[system]||0,score)} / 5</p><div><Button variant="outline" onClick={startQuiz}>Try again</Button><Button onClick={()=>setQuiz(false)}>Back to exploring<ArrowRight/></Button></div></div>:<><div className="quiz-progress"><span>QUESTION {questionIndex+1} OF 5</span><span>{score} correct</span></div><Progress value={questionIndex/5*100} aria-label="Quiz progress"/><h3 className="quiz-question">{question.question}</h3><div className="quiz-options">{question.options.map((option,i)=><button key={option} disabled={answer!==null} className={answer===null?'':i===question.answer?'correct':i===answer?'incorrect':''} onClick={()=>{setAnswer(i);if(i===question.answer)setScore(n=>n+1)}}><span>{String.fromCharCode(65+i)}</span>{option}{answer!==null&&i===question.answer&&<Check size={18}/>}</button>)}</div>{answer!==null&&<div className="answer-explanation" role="status"><strong>{answer===question.answer?'That’s right.':'Here’s the connection.'}</strong><p>{question.explanation}</p><Button onClick={nextQuestion}>{questionIndex===4?'See results':'Next question'}<ArrowRight/></Button></div>}</>}</DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogHeader><DialogTitle>A new perspective on anatomy.</DialogTitle><DialogDescription>Make the most of your atlas.</DialogDescription></DialogHeader><div className="help-content"><p><strong>Rotate</strong>Drag the model with your mouse, or one finger.</p><p><strong>Zoom</strong>Scroll or pinch. The + and − buttons work too.</p><p><strong>Pan</strong>Right-drag with a mouse, or drag with two fingers.</p><p><strong>Select</strong>Click a structure, or click the same spot again to reach the muscle underneath. You can also find it in the searchable list.</p><p><strong>Study</strong>Isolate structures, write notes, and mark what you’ve learned.</p><p><strong>Keyboard</strong>⌘/Ctrl K opens search. Focus the model for +/− zoom, left/right rotation, and 0 to reset.</p></div><p className="help-footer">Your notes and study progress stay in this browser. No account needed.</p></DialogContent></Dialog>
 <Dialog open={sources} onOpenChange={setSources}><DialogContent className="sources-dialog"><DialogHeader><DialogTitle>Built on open anatomy.</DialogTitle><DialogDescription>Model provenance, learning resources, and coverage.</DialogDescription></DialogHeader><div className="sources-content"><h3>3D model attribution</h3><p>Z-Anatomy — the libre 3D atlas of anatomy, by Gauthier Kervyn and Marcin Zielinski, derived from BodyParts3D © The Database Center for Life Science. Z-Anatomy models are shared under <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noreferrer">CC BY-SA 4.0</a>, with additional upstream terms for certain assets. Models are transformed, grouped, and compressed for this viewer.</p><a href="/ATTRIBUTION.md" target="_blank" rel="noreferrer">Model credits & license details<MoveUpRight size={13}/></a><h3>What’s in this atlas</h3>{SYSTEMS.map(s=><p key={s.id}><strong>{s.name}.</strong> {s.coverage}</p>)}<h3>Keep learning</h3><p>The study summaries are introductory learning aids. Models use one reference anatomy and do not represent every anatomical variation.</p><a href="https://training.seer.cancer.gov/anatomy/" target="_blank" rel="noreferrer">NIH / NCI anatomy & physiology modules<MoveUpRight size={13}/></a><p className="educational-note">For anatomy education. Not validated for diagnosis, procedures, or clinical decisions.</p></div></DialogContent></Dialog>
 </main>
}
