export type SystemId = 'skeletal' | 'muscular' | 'nervous' | 'organs' | 'ligaments';
export type Structure = {id:string;name:string;system:SystemId;fma:string;center:number[];bounds:number[];offset:number;vertices:number;indexOffset:number;indices:number};
export const SYSTEMS = [
 {id:'skeletal', name:'Skeletal', subtitle:'The framework of the body',color:'#c7b996',tag:'SUPPORT & PROTECTION',description:'The skeleton supports the body, protects internal organs, and provides attachment points for muscles. Together, bones and joints make movement possible.',facts:['Bone is living tissue that continually remodels.','The axial skeleton includes the skull, spine, and rib cage.','The appendicular skeleton includes the limbs and their girdles.'],coverage:'Individual bones and associated skeletal structures from Z-Anatomy. The number of model meshes is not the number of bones in a person.'},
 {id:'muscular', name:'Muscular', subtitle:'Movement, made possible',color:'#c7776d',tag:'MOVEMENT & POSTURE',description:'Skeletal muscles pull on their attachments to move joints. They also stabilize the body, maintain posture, and produce heat.',facts:['Skeletal muscle is usually under voluntary control.','Muscles often work in opposing groups.','Tendons transmit a muscle’s force to its attachments.'],coverage:'Selected modeled skeletal muscles, including deep and superficial layers. Some source meshes represent muscle parts.'},
 {id:'nervous', name:'Nervous', subtitle:'Connection & coordination',color:'#c6a955',tag:'SENSATION & CONTROL',description:'The brain and spinal cord integrate information and coordinate responses. Cranial and peripheral nerves carry signals between the central nervous system and the rest of the body.',facts:['The brain and spinal cord form the central nervous system.','Gyri are the ridges on the cerebral surface.','Sensory and motor pathways carry different kinds of information.'],coverage:'Brain, spinal cord, cranial nerves, and major peripheral nerves, with selected coverings and landmarks. Fine nerve branches are not exhaustive.'},
 {id:'organs', name:'Organs', subtitle:'The systems that sustain us',color:'#a384bb',tag:'LIFE & HOMEOSTASIS',description:'Internal organs perform specialized tasks, from exchanging gases and circulating blood to digesting food and balancing fluids.',facts:['An organ contains more than one type of tissue.','Organs work together in interconnected systems.','Anatomical left and right refer to the person being studied.'],coverage:'A curated set of major thoracic, abdominal, and pelvic organs. This atlas shows a single adult reference anatomy.'},
 {id:'ligaments', name:'Ligaments', subtitle:'Stability through connection',color:'#71aab8',tag:'CONNECTION & STABILITY',description:'Ligaments are bands of connective tissue that connect and stabilize structures. At many joints, they help guide motion and limit excessive movement.',facts:['Ligaments and tendons have different roles.','Skeletal ligaments generally connect bone to bone.','The long plantar ligament helps support the longitudinal arch of the foot.'],coverage:'Selected shoulder, elbow, wrist, hand, pelvic, and plantar ligaments. This collection does not include knee ligament models.'},
] as const;
export const getSystem = (id:SystemId)=>SYSTEMS.find(s=>s.id===id)!;
type Fact={match:RegExp;summary:string;function:string;remember:string;latin?:string};
const facts:Fact[]=[
 {match:/femur/,latin:'Os femoris',summary:'The femur is the bone of the thigh, extending from the hip to the knee. It is the longest bone in the human body.',function:'Transfers weight from the hip to the knee and provides attachment sites for the muscles that move both joints.',remember:'The femoral head articulates with the acetabulum of the hip bone.'},
 {match:/tibia/,latin:'Tibia',summary:'The tibia is the larger, medial bone of the lower leg. It forms part of both the knee and ankle joints.',function:'Carries most of the weight transmitted through the lower leg.',remember:'The medial malleolus is the prominent inner part of your ankle.'},
 {match:/fibula/,latin:'Fibula',summary:'The fibula is the slender bone on the lateral side of the lower leg, next to the tibia.',function:'Provides muscle attachments and helps stabilize the ankle.',remember:'The lateral malleolus belongs to the fibula.'},
 {match:/humerus/,latin:'Humerus',summary:'The humerus is the long bone of the upper arm, between the shoulder and elbow.',function:'Acts as a lever for arm movement and articulates with the scapula, radius, and ulna.',remember:'The head of the humerus fits into the glenoid cavity of the scapula.'},
 {match:/radius/,latin:'Radius',summary:'The radius is the forearm bone on the thumb side when the body is in anatomical position.',function:'Participates in elbow and wrist movement and rotates around the ulna during pronation.',remember:'Radius = thumb side in anatomical position.'},
 {match:/ulna/,latin:'Ulna',summary:'The ulna is the forearm bone on the little-finger side in anatomical position.',function:'Forms the main hinge with the humerus at the elbow.',remember:'The olecranon of the ulna forms the point of the elbow.'},
 {match:/clavicle/,latin:'Clavicula',summary:'The clavicle, or collarbone, spans the upper chest between the sternum and scapula.',function:'Holds the shoulder away from the trunk and transfers forces from the upper limb to the axial skeleton.',remember:'Its medial end meets the sternum; its lateral end meets the acromion.'},
 {match:/scapula/,latin:'Scapula',summary:'The scapula is a flat, triangular bone on the posterior surface of the thorax.',function:'Provides a mobile base for shoulder movement and numerous muscle attachments.',remember:'The glenoid cavity articulates with the head of the humerus.'},
 {match:/hip bone/,latin:'Os coxae',summary:'Each hip bone is formed by the fused ilium, ischium, and pubis.',function:'Transfers body weight to the lower limbs and contributes to protection of pelvic organs.',remember:'All three parts meet at the acetabulum.'},
 {match:/patella/,latin:'Patella',summary:'The patella is a sesamoid bone within the tendon of the quadriceps muscle at the front of the knee.',function:'Improves the mechanical advantage of knee extension and protects the anterior knee.',remember:'It articulates with the femur.'},
 {match:/vertebra/,summary:'Vertebrae are the individual bones of the vertebral column. Their shape varies between the cervical, thoracic, and lumbar regions.',function:'Support the trunk, protect the spinal cord, and allow controlled movement of the spine.',remember:'A typical vertebra has a body, a vertebral arch, and several processes.'},
 {match:/rib/,latin:'Costa',summary:'Ribs are curved bones of the thoracic wall. They articulate posteriorly with thoracic vertebrae.',function:'Help protect the thoracic organs and participate in breathing movements.',remember:'Most people have 12 pairs of ribs.'},
 {match:/sternum|manubrium|xiphoid/,summary:'The sternum lies in the anterior midline of the chest and consists of the manubrium, body, and xiphoid process.',function:'Provides attachments for the clavicles and costal cartilages and protects underlying structures.',remember:'The sternal angle marks the junction of the manubrium and body.'},
 {match:/mandible/,latin:'Mandibula',summary:'The mandible is the lower jaw bone. It holds the lower teeth and articulates with the temporal bones.',function:'Moves during chewing and speech.',remember:'The temporomandibular joint connects the mandible to the skull.'},
 {match:/sacrum/,latin:'Os sacrum',summary:'The sacrum is a triangular bone formed by fused sacral vertebrae at the base of the spine.',function:'Transfers weight from the vertebral column to the pelvis.',remember:'It articulates laterally with the hip bones at the sacroiliac joints.'},
 {match:/deltoid/,latin:'Musculus deltoideus',summary:'The deltoid is the large muscle that forms the rounded contour of the shoulder.',function:'Its middle fibers abduct the arm; its anterior and posterior fibers contribute to other shoulder movements.',remember:'The axillary nerve supplies the deltoid.'},
 {match:/biceps brachii/,latin:'Musculus biceps brachii',summary:'The biceps brachii is a two-headed muscle in the anterior compartment of the upper arm.',function:'Supinates the forearm and flexes the elbow.',remember:'Its distal tendon attaches to the radial tuberosity.'},
 {match:/triceps brachii/,latin:'Musculus triceps brachii',summary:'The triceps brachii is the three-headed muscle of the posterior upper arm.',function:'Extends the elbow; its long head also acts at the shoulder.',remember:'Its common tendon inserts on the olecranon of the ulna.'},
 {match:/pectoralis major/,summary:'Pectoralis major is a broad, fan-shaped muscle on the anterior chest wall.',function:'Adducts and medially rotates the humerus.',remember:'Its fibers converge toward an attachment on the proximal humerus.'},
 {match:/rectus abdominis/,summary:'Rectus abdominis is a paired muscle running vertically along the front of the abdominal wall.',function:'Flexes the trunk and compresses the abdominal contents.',remember:'Tendinous intersections divide it into visible segments.'},
 {match:/gluteus maximus/,summary:'Gluteus maximus is the large, superficial muscle of the buttock.',function:'Extends and laterally rotates the hip, especially during forceful movement.',remember:'It is particularly active when rising from sitting or climbing stairs.'},
 {match:/gastrocnemius/,summary:'Gastrocnemius is the superficial, two-headed muscle of the posterior calf.',function:'Plantarflexes the ankle and assists knee flexion.',remember:'It crosses both the knee and ankle joints.'},
 {match:/rectus femoris|vastus/,summary:'This muscle is part of the quadriceps group in the anterior thigh.',function:'Extends the knee. Rectus femoris also contributes to hip flexion.',remember:'The quadriceps transmit force through the patella and patellar ligament.'},
 {match:/sartorius/,summary:'Sartorius is a long, strap-like muscle that crosses the front of the thigh obliquely.',function:'Contributes to hip flexion, abduction, and lateral rotation, as well as knee flexion.',remember:'It extends from the anterior superior iliac spine to the medial proximal tibia.'},
 {match:/trapezius/,summary:'Trapezius is a broad, superficial muscle covering the posterior neck and upper back.',function:'Its different fiber groups elevate, retract, depress, and upwardly rotate the scapula.',remember:'The spinal accessory nerve provides its main motor supply.'},
 {match:/heart$/,latin:'Cor',summary:'The heart is a muscular organ in the middle mediastinum, between the lungs.',function:'Pumps blood through the pulmonary and systemic circulations.',remember:'The right side pumps toward the lungs; the left side pumps toward the body.'},
 {match:/lung/,latin:'Pulmo',summary:'The lungs occupy the pleural cavities in the thorax. The right lung has three lobes and the left has two.',function:'Exchange oxygen and carbon dioxide between air and blood.',remember:'Gas exchange occurs across the thin walls of the alveoli and adjacent capillaries.'},
 {match:/liver/,latin:'Hepar',summary:'The liver is a large organ located mainly in the right upper abdomen, beneath the diaphragm.',function:'Processes nutrients, produces bile, synthesizes plasma proteins, and metabolizes many substances.',remember:'The liver receives blood from both the hepatic artery and portal vein.'},
 {match:/stomach/,latin:'Gaster',summary:'The stomach is an expanded part of the digestive tract between the esophagus and small intestine.',function:'Stores and mixes food and begins substantial protein digestion.',remember:'Its outlet into the duodenum is controlled by the pyloric sphincter.'},
 {match:/kidney/,latin:'Ren',summary:'The kidneys are paired, retroperitoneal organs on either side of the vertebral column.',function:'Filter blood and regulate fluid, electrolyte, and acid–base balance.',remember:'Urine flows from each kidney through a ureter to the urinary bladder.'},
 {match:/spleen/,latin:'Splen',summary:'The spleen lies in the left upper abdomen, near the stomach.',function:'Filters blood, helps remove aged blood cells, and supports immune responses.',remember:'The spleen is a lymphatic organ.'},
 {match:/pancreas/,latin:'Pancreas',summary:'The pancreas lies mainly behind the stomach and has both exocrine and endocrine functions.',function:'Produces digestive secretions and hormones including insulin and glucagon.',remember:'The pancreatic head lies within the curve of the duodenum.'},
 {match:/small intestine/,summary:'The small intestine connects the stomach to the large intestine and includes the duodenum, jejunum, and ileum.',function:'Performs most nutrient digestion and absorption.',remember:'Villi and microvilli increase its absorptive surface area.'},
 {match:/large intestine|colon/,summary:'The large intestine includes the cecum, colon, rectum, and anal canal.',function:'Absorbs water and electrolytes and forms and stores feces.',remember:'Its outer longitudinal muscle is concentrated into bands along much of the colon.'},
 {match:/urinary bladder/,summary:'The urinary bladder is a distensible, muscular organ within the pelvis.',function:'Temporarily stores urine before urination.',remember:'The detrusor muscle forms the muscular wall of the bladder.'},
 {match:/trachea/,summary:'The trachea connects the larynx to the main bronchi and lies anterior to the esophagus.',function:'Conducts air to and from the lungs.',remember:'Incomplete cartilage rings help keep the airway open.'},
 {match:/spinal cord/,latin:'Medulla spinalis',summary:'The spinal cord is the part of the central nervous system within the vertebral canal.',function:'Carries information between the brain and body and coordinates many reflexes.',remember:'In adults it usually ends around the L1–L2 vertebral level.'},
 {match:/cerebell/,latin:'Cerebellum',summary:'The cerebellum lies posterior to the brainstem, beneath the occipital lobes.',function:'Helps coordinate movement, balance, and motor learning.',remember:'It refines and coordinates movement rather than initiating voluntary movement.'},
 {match:/precentral/,summary:'The precentral gyrus lies just anterior to the central sulcus in the frontal lobe.',function:'Contains the primary motor cortex, which is involved in voluntary movement.',remember:'Precentral is primarily motor; postcentral is primarily somatosensory.'},
 {match:/postcentral/,summary:'The postcentral gyrus lies just posterior to the central sulcus in the parietal lobe.',function:'Contains the primary somatosensory cortex.',remember:'It processes bodily sensations such as touch and proprioception.'},
 {match:/optic nerve/,summary:'The optic nerve carries visual information from the retina toward the brain.',function:'Transmits the signals used to form vision.',remember:'The optic nerve is cranial nerve II.'},
 {match:/long plantar ligament/,summary:'The long plantar ligament lies on the plantar surface of the foot, spanning from the calcaneus toward the cuboid and metatarsal bases.',function:'Helps stabilize the lateral side of the foot and support the longitudinal arch.',remember:'Plantar refers to the sole of the foot.'},
 {match:/stylohyoid ligament/,summary:'The stylohyoid ligament extends between the styloid process of the temporal bone and the lesser horn of the hyoid.',function:'Contributes to suspension of the hyoid apparatus.',remember:'Its name describes its two attachment regions.'},
 {match:/vocal ligament/,summary:'The vocal ligament is part of the supportive framework of the vocal fold in the larynx.',function:'Contributes to vocal fold tension during sound production.',remember:'It extends between the thyroid cartilage and arytenoid cartilage.'},
 {match:/thyrohyoid|cricothyroid|epiglottic/,summary:'This ligament belongs to the connective tissue framework of the larynx.',function:'Connects and supports adjacent laryngeal structures.',remember:'Ligament names often describe the structures they connect.'},
];
export function describe(s:Structure){const f=facts.find(f=>f.match.test(s.name.toLowerCase()));return f?{...f,specific:true}:{summary:`${s.name} is a modeled structure in the ${getSystem(s.system).name.toLowerCase()} collection. Select Isolate to examine its shape, or show the surrounding anatomy to study its position.`,function:getSystem(s.system).description,remember:getSystem(s.system).facts[0],specific:false,latin:undefined};}
export type Question={question:string;options:string[];answer:number;explanation:string};
export const QUESTIONS:Record<SystemId,Question[]>={
 skeletal:[{question:'Which bone is the longest in the human body?',options:['Humerus','Femur','Tibia','Radius'],answer:1,explanation:'The femur extends from the hip to the knee and is the longest bone.'},{question:'In anatomical position, which forearm bone is on the thumb side?',options:['Ulna','Humerus','Radius','Scapula'],answer:2,explanation:'The radius is on the lateral, or thumb, side of the forearm.'},{question:'The head of the femur articulates with which structure?',options:['Glenoid cavity','Acetabulum','Olecranon','Sternal angle'],answer:1,explanation:'The acetabulum is the socket of the hip joint.'},{question:'Which bone forms the lateral malleolus?',options:['Tibia','Talus','Femur','Fibula'],answer:3,explanation:'The distal fibula forms the prominent outer part of the ankle.'},{question:'Which structure belongs to the axial skeleton?',options:['Femur','Clavicle','Vertebral column','Scapula'],answer:2,explanation:'The axial skeleton includes the skull, vertebral column, and thoracic cage.'}],
 muscular:[{question:'What is the main action of the triceps brachii at the elbow?',options:['Extension','Flexion','Pronation','Supination'],answer:0,explanation:'Triceps brachii extends the elbow through its attachment to the olecranon.'},{question:'Which muscle forms the rounded contour of the shoulder?',options:['Sartorius','Deltoid','Soleus','Rectus abdominis'],answer:1,explanation:'The deltoid covers the shoulder and contributes to arm movement.'},{question:'Which muscle crosses both the knee and ankle?',options:['Deltoid','Pectoralis major','Gastrocnemius','Gluteus maximus'],answer:2,explanation:'Gastrocnemius helps flex the knee and plantarflex the ankle.'},{question:'What does the quadriceps group primarily do?',options:['Flex the wrist','Extend the knee','Rotate the neck','Adduct the arm'],answer:1,explanation:'The quadriceps are the main knee extensors.'},{question:'Which action is performed by biceps brachii?',options:['Elbow extension','Ankle dorsiflexion','Forearm supination','Knee extension'],answer:2,explanation:'Biceps brachii supinates the forearm and flexes the elbow.'}],
 nervous:[{question:'Which structures form the central nervous system?',options:['Brain and spinal cord','All nerves and tendons','Brain and muscles','Heart and brain'],answer:0,explanation:'The brain and spinal cord form the central nervous system.'},{question:'Which brain region helps coordinate movement and balance?',options:['Cerebellum','Optic nerve','Pituitary gland','Spinal root'],answer:0,explanation:'The cerebellum refines movement and supports balance and motor learning.'},{question:'The primary motor cortex lies in which gyrus?',options:['Postcentral','Angular','Precentral','Cingulate'],answer:2,explanation:'The precentral gyrus contains the primary motor cortex.'},{question:'Which cranial nerve carries visual information?',options:['Vagus nerve','Optic nerve','Facial nerve','Hypoglossal nerve'],answer:1,explanation:'The optic nerve is cranial nerve II.'},{question:'What are gyri?',options:['Brain fluid spaces','Ridges on the cerebral surface','Spinal ligaments','Nerve cell nuclei'],answer:1,explanation:'Gyri are surface ridges, separated by grooves called sulci.'}],
 organs:[{question:'Where does most nutrient absorption occur?',options:['Stomach','Esophagus','Small intestine','Urinary bladder'],answer:2,explanation:'The small intestine provides a large surface for nutrient absorption.'},{question:'Which organ produces bile?',options:['Spleen','Liver','Kidney','Heart'],answer:1,explanation:'The liver produces bile; the gallbladder stores and concentrates it.'},{question:'Which organ has both digestive and hormone-producing functions?',options:['Pancreas','Trachea','Spleen','Urinary bladder'],answer:0,explanation:'The pancreas releases digestive secretions and hormones such as insulin.'},{question:'The right side of the heart pumps blood toward the…',options:['Brain only','Liver only','Lungs','Kidneys only'],answer:2,explanation:'The right heart supplies the pulmonary circulation.'},{question:'How many lobes does the right lung normally have?',options:['One','Two','Three','Four'],answer:2,explanation:'The right lung has three lobes; the left has two.'}],
 ligaments:[{question:'What do skeletal ligaments generally connect?',options:['Muscle to skin','Bone to bone','Nerve to muscle','Tendon to nerve'],answer:1,explanation:'Skeletal ligaments generally connect bones and help stabilize joints.'},{question:'The long plantar ligament is located in the…',options:['Shoulder','Neck','Foot','Wrist'],answer:2,explanation:'It lies along the plantar surface of the foot.'},{question:'What does plantar mean?',options:['Toward the head','At the sole of the foot','Behind the spine','Inside the skull'],answer:1,explanation:'Plantar refers to the sole of the foot.'},{question:'The stylohyoid ligament connects toward which bone?',options:['Hyoid','Patella','Radius','Sacrum'],answer:0,explanation:'It extends from the temporal styloid process to the hyoid.'},{question:'How does a tendon usually differ from a ligament?',options:['Tendons transmit muscle force','Tendons are nerves','Tendons contain only bone','Tendons only occur in the skull'],answer:0,explanation:'Tendons transmit muscle force; skeletal ligaments generally connect bones.'}]
};
